version: "3"

services:
  backend:
    build:
      context: ./backend
      # todo:環境変数ごとにDockerfileを分ける
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_PASSWORD: pwd
      DB_DBNAME: goaldb
    env_file:
      - .env
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DBNAME}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - "3306"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
