import Head from "next/head";
import Sidebar from "./Sidebar";

// TODO:chilrenの型を変える
const Layout: React.FC = ({ children }: any) => {
  return (
    <div>
      <Head>
        <title>Goal App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="layout">
        <Sidebar />
        <main>{children}</main>
      </div>
    </div>
  );
};

export default Layout;
