import { Box, Button, Stack, TextField } from "@mui/material";
import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  // TODO:型追加
  const [goals, setGoals] = useState<any>([]);

  const [title, setTitle] = useState<string>("");
  const [text, setText] = useState<string>("");

  useEffect(() => {
    axios.get("http://localhost:8080/goals").then(({ data }) => {
      setGoals(data);
    });
  }, []);

  const addGoal = async () => {
    const goal = {
      title: title,
      text: text,
    };
    const body = new URLSearchParams(goal);
    await axios.post("http://localhost:8080/goal", body).then((res) => {
      getGoals();
    });
  };

  const getGoals = async () => {
    await axios.get("http://localhost:8080/goals").then(({ data }) => {
      setGoals(data);
    });
  };

  return (
    <>
      <Head>
        <title>Top page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>目標を追加する</h2>
        {/* TODO:コンポーネントに分割 */}
        <Box component="form" noValidate autoComplete="off">
          <Stack spacing={2} direction="row">
            <TextField
              id="outlined-read-only-input"
              label="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />
            <TextField
              id="outlined-read-only-input"
              label="text"
              value={text}
              onChange={(e) => setText(e.target.value)}
            />
            <Button onClick={addGoal} variant="contained">
              追加
            </Button>
          </Stack>
        </Box>
        {/* TODO:goal一覧リスト作成 */}
        {goals ? (
          <ul>
            {goals.map((goal, index) => {
              return (
                <li key={index}>
                  <p>
                    title: {goal.title}
                    text: {goal.text}
                  </p>
                </li>
              );
            })}
          </ul>
        ) : (
          <p>null</p>
        )}
      </main>
    </>
  );
}
