name: CI
on: [push]

jobs:
  backend_test:
    name: backend test
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.5"

      - name: Go build & test
        run: |
          cd backend
          go build .
          go test -v

  # build:
  #   runs-on: ubuntu-latest
  #   # defaults:
  #   #   working-directory: backend
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: "1.20.5"
  #         working-directory: backend
  #     - name: Install dependencies
  #       run: go get .
  #     - name: Build
  #       run: go build -v ./...
  #     - name: Test
  #       run: go test -v ./...
